export const smHeadingTexts = {
    rhConstructions: "Leading Construction Company in Brooklyn",
    aboutUs: "About Us",
    trustUs: "Trust us",
    ourServices: "Services",
    workingProcess: "Working Process",
    review: "Review",
    gallery: "Gallery",
    expContractor: "Experienced Contractor",
    rightContractorChoosing: "Right Contractor Choosing",
    projectWithUs: "Projects with RH",
    toolsNEquip: "Tools & Equipment's",
    projectCost: "Project Cost",
    faq: "FAQ",
    contractors: "Contractors",
    area: "Area",
}
